subscription_id = "Enter your own Subscription ID"
client_id = "Enter Your created Application Client ID"
client_secret = "Enter Your created Application Password"
tenant_id = "Enter your Tenant ID"
location ="Enter the Azure resource region"
hostname = "Enter your VMs Hostname"
admin_username = "Enter your VMs username"
admin_password = "Enter the password for your VMs"